pipeline {
    agent any

    tools {
        jdk 'JDK21'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/AbelBusi/software-gestion-interna-constructora.git'
            }
        }

        stage('Build & Test') {
            steps {
                bat '.\\mvnw.cmd clean verify'
            }
        }

        stage('Package') {
            steps {
                bat '.\\mvnw.cmd package -DskipTests'
            }
        }

        stage('Archive Artifacts') {
            steps {
                archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            }
        }
    }

    post {
        success {
            echo 'Build exitoso'
        }
        failure {
            echo 'Build falló'
        }
    }
}